### PR TITLE
Nix Action

### PR DESCRIPTION
**Pull request by Zimmi48**
Draft PR for testing

### CODE REVIEW

**Comment by Zimmi48** [comment]
Nix is the fastest!

**Comment by Zimmi48** [comment]
This now corresponds to the output of the template found in coq-community/templates#81.

**Comment by erikmd** [comment]
Thanks @Zimmi48 and @CohenCyril !

> Nix is the fastest!

are you sure? :smiley: − I had the impression it was not fully the case, as each Docker job build took less than 2mn26:
https://github.com/coq-community/huffman/pull/24/checks?check_run_id=1513539528
and the Nix build took 2mn36:
https://github.com/coq-community/huffman/pull/24/checks?check_run_id=1513539337
so maybe this was due to the fact there are more jobs in the docker-coq-action, which weren't started at the same time…

**Comment by Zimmi48** [comment]
Ah maybe that's so. When I posted the comment, only the Nix job was complete, but some jobs may have been pending for longer than others.

**Pull request merged**
